---
version: 2.1

orbs:
  lsif-go: sourcegraph/lsif-go@0.1.0
  lsif-upload: sourcegraph/lsif-upload@0.1.0

jobs:
  build:
    working_directory: ~/helm.sh/helm
    docker:
      - image: circleci/golang:1.13

    environment:
      GOCACHE: "/tmp/go/cache"
      GOLANGCI_LINT_VERSION: "1.21.0"

    steps:
      - checkout
      - run:
          name: install test dependencies
          command: .circleci/bootstrap.sh
      - run:
          name: test style
          command: make test-style
      - run:
          name: test
          command: make test-coverage
      - deploy:
          name: deploy
          command: .circleci/deploy.sh

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

  sourcegraph-index:
    jobs:
      - lsif-go/build-index
      - lsif-upload/upload-index:
          github-token: ${SRC_GITHUB_TOKEN}
          requires:
            - lsif-go/build-index
